### ISSUE TITLE
Mapper 22/23 mirroring selection inaccurately emulated

### ISSUE THREAD

**Issue by koitsu** [rdanbrook/nestopia#172] opened 2016-04-04 11:39 UTC
Issue: Mapper 22 (VRC2a) and 23 (VRC2b) mirroring selection ($9000-9003) is inaccurately emulated.

Details: For some time, VRC2a/2b reverse-engineering documentation has been incorrect (docs by Goroh and Disch are incorrect); said docs stated VRC2a/2b supported 4 different modes of mirroring (H, V,  1-screen (lower), 1-screen (upper)), similar to VRC4.

This has been fully debunked through several means (incl. but not limited to translation of official Konami VRC2 docs).  It's been determined that VRC2a/2b only implements H/V mirroring, controlled via bit 0; there is no 1-screen support in VRC2a/2b.

Inaccurate emulation of this register manifests itself badly in Konami's Wai Wai World (mapper 23), where in late stages of the game -- particularly parts of the overhead vertically-scrolling shooter stage, and the staff roll/credits -- graphics appear corrupted.

Fix: patch not available, but the proper solution is to only honour bit 0 of writes to $9000-9003 registers (0=V, 1=H).

Save states for testing (.zip file):
* Download: https://www.dropbox.com/s/9bij8iv41rvr6x1/Wai%20Wai%20World%20%28J%29.states.zip?dl=0
* For use with ROM: Wai Wai World (J).nes -- MD5 752353ccc6678c727926b661c7ad5e3f
* ns1 = Press Start, jump into the ship; "boss graphics" corrupted, and very ending screen after staff roll is corrupted
* ns2 = Part of the vertically-scrolling stage (demo/attract mode); graphics (mid-screen) during panning are corrupted

References:
* Video: https://www.youtube.com/watch?v=501HIakfGQs&t=2h15m0s
* Video: https://www.youtube.com/watch?v=501HIakfGQs&t=2h32m39s
* Full analysis: http://forums.nesdev.com/viewtopic.php?f=3&t=13473
* Wiki: http://wiki.nesdev.com/w/index.php/VRC2

**Comment by lidnariq** [comment] 2016-04-04 16:33
Please note that I already tried switching the line in KonamiVrc2.cpp from
`Map( 0x9000U, 0x9FFFU, NMT_SWAP_VH01 );`
to
`Map( 0x9000U, 0x9FFFU, NMT_SWAP_VH );`
and it tickled some unrelated mirroring bug.

**Comment by dragon2snow** [comment] 2016-04-06 08:28
![2016-04-06_16-23-14](https://cloud.githubusercontent.com/assets/4350811/14310455/8193aae8-fc14-11e5-9768-83c8afb14ff1.png)
![2016-04-06_16-25-51](https://cloud.githubusercontent.com/assets/4350811/14310457/82498fe8-fc14-11e5-8ffb-234a99872069.png)

You to test all VRC2 game!

**Comment by dragon2snow** [comment] 2016-04-06 08:46
VRC2 is h,v,0,1,but wai wai world ...

**Comment by koitsu** [comment] 2016-04-06 08:52
We have confirmed repeatedly (on actual hardware, and per official Konami documentation) that VRC2 does not support single-screen mirroring.  Please see the References links for details, especially the nesdev forum thread, which includes testing on actual hardware.

If you have evidence of one-screen mirroring on an actual VRC2 game, we'd love to know it.  All that's been shown so far is anecdotal classic documentation that seems to be based off of VRC4 (which does support H/V/1-screen).

**Comment by dragon2snow** [comment] 2016-04-06 09:04
try my fixed.

**Comment by koitsu** [comment] 2016-04-06 09:57
The 0xFF comparison "quirk" has already been discussed in the nesdev thread by the same person as here (lidnariq), which is what FCEUX does.  And it was agreed that it's an incorrect hack.  We even tried to track down the history/reason for this hack, but it was so long ago that it wasn't in FCEUX's commit history.  It was concluded that the 0xFF comparison hack was chosen a long time ago to make Wai Wai World work, because the emulator was developed with the belief (based on docs from Firebug and Goroh) that VRC2a/2b support one-screen.

However, the core of the matter is that VRC2a/VRC2b, from testing on actual hardware, shows that there is no one-screen mirroring support, only H/V.  In other words: only bit 0 of the mirror toggle registers is honoured on mappers 22 and 23.

If you have knowledge of real VRC2a/VRC2b games that have VRC2 chips that do support one-screen mirroring support, please list off the game titles.  We can have someone run the test ROM (see nesdev thread) on those carts to verify.

**Comment by dragon2snow** [comment] 2016-04-08 05:47
`
NES_POKE_AD(Vrc2, 9000)
				{
					static const byte lut[1][4] =
					{
						{ 0,1,0,1 },
						{ 0,0,1,1 }
					};

					ppu.SetMirroring(lut[data & 0x1]);
				}`
but This is a bad,because VRC2 unofficial game  have four screen support.

**Comment by koitsu** [comment] 2016-04-08 06:04
Do you have a list of *those* games?

**Comment by koitsu** [comment] 2016-04-12 18:24
BizHawk (NesHawk) just implemented this change, doing it in a fairly cute way, specifically for mapper 23: they use a variable to differentiate between VRC4e/4f (type=4) and VRC2b (type=2) games.  Then for the actual bitmask on writes to the mirroring registers, they use (type-1) (so VRC4 = & 3 and VRC2 = & 1).  https://github.com/TASVideos/BizHawk/commit/ef544cd9aba733c20350731f718fdd46edf9fdd1

I thought I'd mention it here since a similar method might be easier to implement in Nestopia.

**Comment by lidnariq** [comment] 2016-04-12 19:02
The only blocking issue on this bug is figuring out why Wai Wai World bugs (i.e. fails to draw the computer in the background during attract mode) when using NMT_SWAP_HV.

Unfortunately, since Nestopia lacks a debugger, figuring out what's going wrong is hard.

Because Nestopia already emulates the VRC2 and VRC4 separately, there's no need for FCEUX's hack, or BizHawk's separation.

**Comment by dragon2snow** [comment] 2016-04-12 22:58
![qq 20160413065514](https://cloud.githubusercontent.com/assets/4350811/14478092/18bfb8dc-0145-11e6-8451-29cd070d2e47.png)

**Comment by joepogo** [comment] 2016-04-13 21:07
Where is this file located dragon2snow?

**Comment by lidnariq** [comment] 2016-04-13 21:17
That's his modified private fork of Nestopia, borrowing the fix from puNES.

There is no need to copypasta like this. Just use NMT_SWAP_VH instead of NMT_SWAP_HV01.

**Comment by joepogo** [comment] 2016-04-13 21:18
Thanks lidnariq, Im trying to figure out where to do this little fix. Im assuming in boards/vrc2?

**Comment by lidnariq** [comment] 2016-04-13 21:32
I brainoed on what the original was. Fixed now.

**Comment by rdanbrook** [comment] 2016-04-14 03:52
Just so everyone knows, I am paying attention to this issue. I will deal with it soon.

**Comment by lidnariq** [comment] 2016-04-14 05:11
joepogo: Change it from VH01 to **HV**

The problem is that VH01 means "values of 0,1,2,3 are respectively vertical,horizontal,1scA,1scB" but VH means "values of 0,1 are horizontal,vertical":
```
    NES_POKE_D(Board,Nmt_Vh)
    {
        NST_VERIFY( data <= 0x1 );
        ppu.SetMirroring( (data & 0x1) ? Ppu::NMT_V : Ppu::NMT_H );
    }
```
This awkward naming convention is what made this bug report go through this long confusing side trip when it's a trivial change.

Perhaps that confusingness should be given its own bug report?

**Comment by joepogo** [comment] 2016-04-14 15:24
Sorry for the late reply. Thanks lidnariq! Yea, I changed the VH01 to HV and it works like a charm. Im surprised most fixes for nestopia seem to be very trivial with minimal changes despite the C++ goo spattered everywhere. 

Any chance this related to this?:

https://github.com/rdanbrook/nestopia/issues/147

**Comment by rdanbrook** [comment] 2016-04-24 15:27
Thanks everyone for doing the analysis and hard work. I just committed the fix.

**Closed by rdanbrook** 2016-04-24 15:27 UTC
