### ISSUE TITLE
screenshot creates empty png's

### ISSUE THREAD

**Issue by cbeach** [rdanbrook/nestopia#138] opened 2015-04-12 04:54 UTC
I was trying to create a series of screenshots for an upcoming project.
I set the code up so that is would take a screen shots using video.cpp:video_screenshot.
Unfortunately this produced blank/transparrent/empty png's.

**Comment by rdanbrook** [comment] 2015-04-12 22:05
Can you show me the code?

**Comment by cbeach** [comment] 2015-04-13 19:42
The error actually shows up when I try to take a screen shot from the gui as well. I

**Comment by cbeach** [comment] 2015-04-13 19:53
Sorry, wrong button :(
I had the same issue while trying to save a screenshot via the GUI.
Any call to source/unix/video.cpp:video_screenshot (line 620) failed in the same way.
I'm calling video_screenshot function in the else block at source/unix/main.cpp:1023

I don't have access to the code at the moment. I'll make sure to post it when I get home.

**Comment by cbeach** [comment] 2015-04-14 02:26
I just pushed the changes that I made to my fork.
The changes were made to source/unix/main.cpp starting at line 1025.

**Comment by rdanbrook** [comment] 2015-04-14 02:40
I'm not on a device that I can test this on right now, but try moving your code changes to source/unix/video.cpp after line 602.

The screenshot function is using glReadPixels. Are you able to save screenshots from my master branch with no changes?

**Comment by cbeach** [comment] 2015-04-15 04:10
I found the bug while working on my laptop. I just tried it on my desktop and it seems to be working fine. It looks like it's a local configuration issue. I'll post the specifications for my laptop if you'd like.

**Comment by rdanbrook** [comment] 2015-04-16 00:03
Yeah, that would be great. I am mostly interested in knowing the video card and driver in use.

**Comment by rdanbrook** [comment] 2015-05-07 02:56
I'm gonna close this, since the issue seems to be isolated, and I don't have information to reproduce it.

**Closed by rdanbrook** 2015-05-07 02:56 UTC
