### ISSUE TITLE
Ms.Pacman Tengen unplayable

### ISSUE THREAD

**Issue by jjfmz42015** [rdanbrook/nestopia#176] opened 2016-04-25 14:00 UTC
Ms.Pacman Tengen unplayable not licensed version but the better tengen version.

Works on Nestopia WIN32 but fails on Nestopia WINALPHA

the only emulator I have ever seen run this on windows was Nestopia.

**Comment by rdanbrook** [comment] 2016-04-25 16:17
It works for me on Linux and OS X. It is probably just an issue with the Windows build of that same source. You've given me incentive to improve that port!

**Comment by jjfmz42015** [comment] 2016-04-25 17:15
Your sure its the Tengen version?

It doesnt work on any other emulator on windows and I have not tested your build on linux or osx yet but last time i tried retro arch on linux with nestopia core the tengen ms pac man rom didnt work either.


There are two ms pac man versions on NES one works on all emulators one is known to work only on nestopia for windows.

filename "Ms. Pac-Man (Tengen) [!].nes" crc32 A4A116F1

**Comment by rdanbrook** [comment] 2016-04-25 20:34
Ms. Pac-Man (USA) (Unl).nes
BD0E29B3 - crc32 with header
43D30C2F - crc32 without header

So I guess it is a different dump, but it is definitely the Tengen version of the game. I do have a goodset laying around still, so let me take a look and see if the dump from the goodset is different from the no-intro set.

**Comment by jjfmz42015** [comment] 2016-04-25 23:15
ok strange. my roms were all run through goodnes so i thought they were good.

just found that if i "repair" the header on my "good rom" it now works on all the emus not just nestopia.

confused as to how goodnes called it good but now i fixed it using goodnes.

**Comment by rdanbrook** [comment] 2016-04-25 23:21
GoodNES is obsolete at this point, and most people are using no-intro sets these days. The Bootgod DB is probably the best place to get accurate information about cartridges.

It seems like this is a bad dump. I don't have the same one, so I can't look at it, but the size may be wrong or something. It could have corrupted or missing data.

**Comment by jjfmz42015** [comment] 2016-04-25 23:29
true no intro sets have no header which makes them useless in emulation doesnt it? im confused.

**Comment by rdanbrook** [comment] 2016-04-25 23:38
That's a whole other rabbit hole. I went down that rabbit hole and wrote a program to modify rom headers that eventually evolved into this: https://github.com/rdanbrook/cirugia

I'm closing this, since I can't reproduce it with any of the "officially good" roms.

**Closed by rdanbrook** 2016-04-25 23:38 UTC

**Comment by jjfmz42015** [comment] 2016-04-27 15:19
GoodNES fix nes option fixed my rom headers. my crc on my ms pac man is now B6D2D300 like yours and is fine.
