### ISSUE TITLE
Stuttering sound

### ISSUE THREAD

**Issue by someguy21** [rdanbrook/nestopia#112] opened 2014-12-26 16:25 UTC
There seems to be some kind of sound issue with Nestopia, often when I run it the sound is really ..well weird. Sounds kinda like there isn't enough CPU power or such but Nestopia worked fine before on this computer. Nestopia on Retroarch works fine too. Maybe it's a libao thing.

**Comment by rdanbrook** [comment] 2015-03-12 21:41
Closing due to lack of information required to reproduce or diagnose the issue.

**Closed by rdanbrook** 2015-03-12 21:41 UTC
